#
# Docker compose file for dockerized ROS Nodes for phleet car
# Author: Alex Wroblewski
#
version: '0.1'

# Create a bridged network named 'ros'
#
networks:
  ros:
    driver: bridge

# Define the services in the docker compose file.
#
services:
  # Currently - the ROS Master is just the kinetic-ros-core.
  # We may do something more fancy in the future.
  #
  ros-master:
    image: ros:kinetic-ros-core
    command: roscore
    networks:
      - ros
    restart: always

  # Define the steering node.
  #
  steering:
      image: philly-phleet/steering
      command: ./entry
      networks:
        - ros
      restart: always

  # Define the LIDAR NODE
  #
  lidar:
      image: philly-phleet/lidar
      command: ./entry
      networks:
        - ros
      args:
        - device=/dev/ttyUSB0
      restart: always

  # These talker and Listener nodes are used to verify the integrity of the composed network
  #
  talker:
    image: ros:kinetic-ros-core
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=talker"
    command: stdbuf -o L rostopic pub /chatter std_msgs/String "hello" -r 1
    networks:
      - ros
    restart: always

  listener:
    image: ros:kinetic-ros-core
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=listener"
    command: stdbuf -o L rostopic echo /chatter
    networks:
      - ros
    restart: always